### ISSUE TITLE
Mac版本的K8S是否需要安装tiller？

### ISSUE THREAD

**Issue by chaoyue729** [gotok8s/gotok8s#20]
想问一下楼主，mac安装helm是通过brew或者下载tar文件，但是没有看到tiller的下载安装呢？

**Comment by maguowei** [comment]
@chaoyue729  最新的 helm3 不再需要安装 tiller了 https://helm.sh/docs/faq/#removal-of-tiller

brew 安装就行，默认安装的已经是helm3
